### ISSUE TITLE
Typo in the export json "messageForIncorrectAnswer"

### ISSUE THREAD

**Issue by alibslh** [wingkwong/react-quiz-form#3]
I was using the exported json and I noticed that it does not export the fields properly.

the field `messageForIncorrectAnswer` exported as `messageForInorrectAnswer` missing the `c` in Incorrect.

 
![image](https://user-images.githubusercontent.com/17546879/81396002-4b3bfd80-912d-11ea-9e20-9110134325d9.png)

**Comment by yun-sangho** [comment]
May I take this one?

**Comment by wingkwong** [comment]
@yun-sangho 네
